### ISSUE TITLE
macOS guidance

### ISSUE THREAD

**Issue by nemphys** [wulf7/iwmbt-firmware#2]
Hi, I would appreciate any hints on how to get this working on macOS (since it is stated in the readme that it should be easy to implement).
Right now, the only option is to first boot Windows/Linux in order to get the bluetooth firmware downloaded to the adapter, which is not optimal.

**Comment by wulf7** [comment]
I successfully compiled iwmbt-firmware on MacOSX 10.13 VM and committed required changes to the project. So try latest snapshot.

P.S. Not tested on real hardware

**Comment by nemphys** [comment]
Nice!
I built this successfully and managed to get the firmware downloaded to the internal bluetooth card of my NUC8i7BEH hackintosh!
The only problem is that it could not claim the usb interface until I first unloaded the bluetooth related kexts. I then had to reboot, since reloading them did not make the card operational.

Edit: Just unloading/reloading com.apple.iokit.IOBluetoothHostControllerUSBTransport before/after the firmware download works without a reboot.

**Comment by wulf7** [comment]
> Edit: Just unloading/reloading com.apple.iokit.IOBluetoothHostControllerUSBTransport before/after the firmware download works without a reboot.

Really, upstream project (btstack) code is not designed to return control of bt device to operating system after it has been run. I added some hacks to fix that for FreeBSD but they did not work very well for me and looks like they don't work at all for MacOSX. So I think, unloading the driver before downloader start and loading it again after finish is the best that can be done currently.

**Comment by nemphys** [comment]
Great, really appreciate your effort, solved a long-standing issue!
